# Generated by Django 5.0 on 2026-04-29 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodiumSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_sum', models.BigIntegerField()),
                ('submitted_by', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('invalid', 'Invalid')], default='pending', max_length=20)),
                ('stage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('required_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resolved_manually', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='game.run')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('username_key', models.CharField(max_length=80)),
                ('current_stage', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('is_test_user', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.run')),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StageCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('code', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_codes', to='game.player')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_codes', to='game.run')),
            ],
            options={
                'ordering': ['player_id', 'stage'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('player_ids', models.JSONField(default=list)),
                ('player_usernames', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='game.podiumsubmission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('run', 'username_key'), name='uniq_player_name_per_run'),
        ),
        migrations.AddConstraint(
            model_name='stagecode',
            constraint=models.UniqueConstraint(fields=('player', 'stage'), name='uniq_stage_code_per_player_stage'),
        ),
        migrations.AddConstraint(
            model_name='stagecode',
            constraint=models.UniqueConstraint(fields=('run', 'stage', 'code'), name='uniq_stage_code_per_run_stage'),
        ),
    ]
