# Generated by Django 5.0.14 on 2026-04-29 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_checker_fail_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='checker_verified_stage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
