# Generated by Django 5.0.14 on 2026-04-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_checker_verified_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='podiumsubmission',
            name='progressed_usernames',
            field=models.JSONField(default=list),
        ),
    ]
