# Generated by Django 5.0.14 on 2026-04-29 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_podiumsubmission_progressed_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='collaboration_size_cap',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
