# Generated by Django 5.0.14 on 2026-04-29 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_run_collaboration_size_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='orientation_collapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='orientation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='orientation_device_type',
            field=models.CharField(blank=True, choices=[('own', 'Own Device'), ('uol', 'University of Liverpool Machine')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='orientation_language',
            field=models.CharField(blank=True, choices=[('r', 'R'), ('python', 'Python'), ('javascript', 'JavaScript')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='orientation_os',
            field=models.CharField(blank=True, choices=[('windows', 'Windows'), ('mac', 'Mac'), ('chromebook', 'Chromebook'), ('linux', 'Linux')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='orientation_step',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
