# Generated by Django 5.0 on 2026-04-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_orientation_collapsed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='intro_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
