# Generated by Django 4.2.3 on 2026-04-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_player_intro_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
