# Generated by Django 4.2.3 on 2026-04-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_player_checker_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerfeedback',
            name='likert_responses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='playerfeedback',
            name='open_responses',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
