# Generated by Django 5.0.14 on 2026-08-18 11:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_playerfeedback_likert_responses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Fight The Future', max_length=200)),
                ('event_date', models.CharField(blank=True, max_length=120)),
                ('event_time', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('permitted_email_domain', models.CharField(default='liverpool.ac.uk', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'event settings',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('email_key', models.CharField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='game.eventsettings')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
