# Generated by Django 5.0.14 on 2026-08-18 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_eventsettings_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='registration_limit',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
