# Generated by Django 5.0.14 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_eventsettings_registration_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="orientation_device_type",
            field=models.CharField(
                blank=True,
                choices=[("codespace", "Use GitHub Codespace")],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="orientation_language",
            field=models.CharField(
                blank=True,
                choices=[("r", "R"), ("python", "Python")],
                max_length=16,
                null=True,
            ),
        ),
    ]
