# Generated by Django 5.0.14 on 2026-09-14

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [("game", "0013_alter_player_orientation_device_type_and_more")]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="orientation_step",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)],
            ),
        ),
    ]
