# Generated by Django 5.0.14 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("game", "0014_alter_player_orientation_step")]

    operations = [
        migrations.AddField(
            model_name="eventsettings",
            name="registration_close_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
