#!/usr/bin/env python3
"""
Generate offline contingency datasets using the existing Django stage generators.

Outputs:
- One folder per participant with stage datasets exactly as generated by dataset_download_view
- teacher_answer_sheet.csv with personal 6-digit codes per stage
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import sys
from datetime import datetime
from pathlib import Path


def _project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _setup_django() -> None:
    root = _project_root()
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

    import django

    django.setup()


def _ensure_schema() -> None:
    from django.core.management import call_command

    # Safe to run repeatedly; applies only pending migrations.
    call_command("migrate", interactive=False, verbosity=0)


def _safe_name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]", "_", value)


def _dataset_filename_for_stage(stage: int) -> str:
    if stage == 3:
        return "stage3_signal_readings.csv"
    if stage == 4:
        return "stage4_drone_fleet.zip"
    return f"stage{stage}_dataset.csv"


def _write_dataset_for_stage(player_id: int, stage: int, output_path: Path) -> None:
    from django.test import RequestFactory

    from game.views import dataset_download_view

    factory = RequestFactory()
    request = factory.get(f"/play/{player_id}/dataset/{stage}")
    response = dataset_download_view(request, user_id=player_id, stage=stage)

    if response.status_code != 200:
        raise RuntimeError(
            f"Dataset generation failed for player_id={player_id}, stage={stage}, "
            f"status={response.status_code}"
        )
    output_path.write_bytes(response.content)


def _write_stage_markdown(stage: int, output_path: Path) -> None:
    from game.stage_content import get_stage_content

    content = get_stage_content(stage)
    title = str(content.get("title") or f"Stage {stage}")
    narrative = str(content.get("narrative") or "").strip()
    instructions = content.get("instructions") or []

    lines: list[str] = [f"# {title}", ""]
    if narrative:
        lines.append("## Narrative")
        lines.append("")
        lines.append(narrative)
        lines.append("")

    lines.append("## Instructions")
    lines.append("")
    if instructions:
        for idx, item in enumerate(instructions, start=1):
            lines.append(f"{idx}. {item}")
    else:
        lines.append("_No instructions defined._")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate offline contingency datasets and teacher answer sheet."
    )
    parser.add_argument(
        "-n",
        "--count",
        type=int,
        required=True,
        help="Number of personalised dataset packs to generate.",
    )
    parser.add_argument(
        "--username-prefix",
        default="contingency",
        help="Prefix for generated usernames (default: contingency).",
    )
    parser.add_argument(
        "--output-dir",
        default="contingency/output",
        help="Base output directory (default: contingency/output).",
    )
    parser.add_argument(
        "--run-name",
        default=None,
        help="Optional run name. If omitted, a timestamped name is used.",
    )
    args = parser.parse_args()

    if args.count < 1:
        raise SystemExit("--count must be at least 1")

    _setup_django()
    _ensure_schema()

    from django.db import transaction

    from game.constants import STAGE_COUNT
    from game.models import Run, StageCode
    from game.services import create_player

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_name = args.run_name or f"contingency_{stamp}"
    base_output = Path(args.output_dir).resolve()
    run_output = base_output / _safe_name(run_name)
    run_output.mkdir(parents=True, exist_ok=True)

    players: list[tuple[str, int]] = []

    # Keep this run out of live flow by explicitly setting is_current=False.
    with transaction.atomic():
        run = Run.objects.create(
            name=run_name,
            status=Run.Status.ACTIVE,
            is_current=False,
        )
        for idx in range(1, args.count + 1):
            username = f"{args.username_prefix}{idx:03d}"
            player = create_player(run, username, is_test_user=True)
            players.append((player.username, player.id))

    answer_rows: list[dict[str, int | str]] = []
    for username, player_id in players:
        player_dir = run_output / _safe_name(username)
        player_dir.mkdir(parents=True, exist_ok=True)

        for stage in range(1, STAGE_COUNT + 1):
            stage_dir = player_dir / f"stage_{stage}"
            stage_dir.mkdir(parents=True, exist_ok=True)

            stage_filename = _dataset_filename_for_stage(stage)
            stage_output = stage_dir / stage_filename
            _write_dataset_for_stage(player_id, stage, stage_output)
            _write_stage_markdown(stage, stage_dir / "instructions.md")

        stage_codes = {
            row.stage: row.code
            for row in StageCode.objects.filter(player_id=player_id).order_by("stage")
        }
        answer_rows.append(
            {
                "username": username,
                "player_id": player_id,
                "stage_1_code": stage_codes.get(1, ""),
                "stage_2_code": stage_codes.get(2, ""),
                "stage_3_code": stage_codes.get(3, ""),
                "stage_4_code": stage_codes.get(4, ""),
            }
        )

    answer_sheet_path = run_output / "teacher_answer_sheet.csv"
    with answer_sheet_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "username",
                "player_id",
                "stage_1_code",
                "stage_2_code",
                "stage_3_code",
                "stage_4_code",
            ],
        )
        writer.writeheader()
        writer.writerows(answer_rows)

    print(f"Run: {run.name} (id={run.id})")
    print(f"Generated packs: {len(players)}")
    print(f"Output folder: {run_output}")
    print(f"Teacher answer sheet: {answer_sheet_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
